begin;
insert into auth.users(id,aud,role,email,created_at,updated_at) values
('ef110000-0000-4000-8000-000000000037','authenticated','authenticated','xian-wall-test@example.invalid',now(),now());
select set_config('request.jwt.claim.sub','ef110000-0000-4000-8000-000000000037',true);
set local role authenticated;
do $$ declare r jsonb; before_state jsonb; req uuid:=gen_random_uuid();failed bool;begin
 r:=public.xian_action('create','{"name":"ทดสอบกำแพง","map":"bamboo"}',gen_random_uuid());
 r:=public.xian_action('wall_line','{"x":2,"y":2,"end_x":5,"end_y":2}',req);
 assert jsonb_array_length(r->'state'->'buildings')=6;
 assert (r->'state'->>'water')::numeric=630 and (r->'state'->>'rice')::numeric=630,'Wrong row cost';
 r:=public.xian_action('wall_line','{"x":2,"y":2,"end_x":5,"end_y":2}',req);
 assert jsonb_array_length(r->'state'->'buildings')=6 and (r->'state'->>'water')::numeric=630,'Replay charges twice';
 r:=public.xian_action('wall_edit','{"index":2,"operation":"rotate"}',gen_random_uuid());
 assert r->'state'->'buildings'->5->>'x'='2' and r->'state'->'buildings'->5->>'y'='5';
 assert r->'state'->'buildings'->2->>'rotation'='1';
 before_state:=r->'state';failed:=false;
 begin perform public.xian_action('wall_edit','{"index":2,"operation":"rotate"}',gen_random_uuid());exception when others then failed:=true;end;
 assert failed,'Out-of-bounds rotation accepted';
 r:=public.xian_action('sync','{}',gen_random_uuid());assert r->'state'=before_state,'Failed rotate partially changed state';
 r:=public.xian_action('wall_edit','{"index":2,"operation":"move","x":4,"y":8}',gen_random_uuid());
 assert r->'state'->'buildings'->5->>'x'='4' and r->'state'->'buildings'->5->>'y'='11';
 before_state:=r->'state';failed:=false;
 begin perform public.xian_action('wall_edit','{"index":2,"operation":"move","x":7,"y":6}',gen_random_uuid());exception when others then failed:=true;end;
 assert failed,'Wall run can move through hall';
 r:=public.xian_action('sync','{}',gen_random_uuid());assert r->'state'=before_state,'Failed move partially changed state';
 failed:=false;
 begin perform public.xian_action('wall_line','{"x":1,"y":1,"end_x":3,"end_y":3}',gen_random_uuid());exception when others then failed:=true;end;
 assert failed,'Diagonal wall request accepted';
 failed:=false;
 begin perform public.xian_action('wall_edit','{"index":0,"operation":"rotate"}',gen_random_uuid());exception when others then failed:=true;end;
 assert failed,'Wall editor accepted a hall';
 failed:=false;
 begin perform public.xian_action('wall_line','{"x":0,"y":7,"end_x":15,"end_y":7}',gen_random_uuid());exception when others then failed:=true;end;
 assert failed,'Wall line can cross existing buildings';
 r:=public.xian_action('sync','{}',gen_random_uuid());assert r->'state'=before_state,'Failed line charged resources or placed partial walls';
end $$;
reset role;
select 'XIAN_WALL_TESTS_PASSED' as result;
rollback;
