plugins { id 'com.android.application' }

android {
    namespace 'com.skywings.reborn'
    compileSdk 36

    defaultConfig {
        applicationId 'com.skywings.reborn'
        minSdk 23
        targetSdk 36
        versionCode 14
        versionName '3.1-rts-playable'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
