package com.skywings.reborn;

import android.content.Context;
import android.content.Intent;
import android.graphics.*;
import android.net.Uri;
import android.view.MotionEvent;
import android.view.View;
import java.util.ArrayList;
import java.util.Random;

public class GameView extends View {
    private static final String MONETAG_URL="https://omg10.com/4/10852115";
    private static final int MENU=0,PLAY=1,DEAD=2,CLEAR=3;
    private static class O{float x,y,vx,vy,r;int type,hp;boolean alive=true;O(float x,float y,float r,int t){this.x=x;this.y=y;this.r=r;this.type=t;}}
    private static class P{float x,y,vx,vy,life,size;int c;P(float x,float y,float vx,float vy,float l,float s,int c){this.x=x;this.y=y;this.vx=vx;this.vy=vy;this.life=l;this.size=s;this.c=c;}}
    private final Paint p=new Paint(3); private final Random rnd=new Random();
    private final ArrayList<O> enemies=new ArrayList<>(),shots=new ArrayList<>(),enemyShots=new ArrayList<>(),drops=new ArrayList<>();
    private final ArrayList<P> particles=new ArrayList<>(); private final ArrayList<O> stars=new ArrayList<>();
    private final String[] ships={"FALCON","VIPER","PHANTOM","TYPHOON","AEGIS"};
    private final int[] shipC={Color.rgb(50,225,255),Color.rgb(255,70,105),Color.rgb(255,190,45),Color.rgb(190,90,255),Color.rgb(215,250,255)};
    private final int[] enemyC={Color.rgb(255,55,100),Color.rgb(255,145,45),Color.rgb(185,65,255),Color.rgb(40,225,185),Color.rgb(55,150,255),Color.rgb(255,55,190)};
    private int mode=MENU,stage=1,ship=0,score=0,coins=0,gems=0,hp=100,power=1,shield=1,bomb=2,kills=0,target=8,W,H; private float px,py;
    private boolean boss=false,bombFlash=false; private long last,spawnClock,shotClock,enemyClock,bombClock;
    public GameView(Context c){super(c);setFocusable(true);setClickable(true);setLayerType(View.LAYER_TYPE_SOFTWARE,null);for(int i=0;i<150;i++){O s=new O(rnd.nextInt(1000),rnd.nextInt(1800),.6f+rnd.nextFloat()*2,0);s.vy=.4f+rnd.nextFloat()*1.5f;stars.add(s);}last=System.currentTimeMillis();}
    private void txt(Canvas c,String s,float x,float y,float z,int col,Paint.Align a){p.setStyle(Paint.Style.FILL);p.setShader(null);p.setColor(col);p.setTextSize(z);p.setTextAlign(a);p.setTypeface(Typeface.create("sans",Typeface.BOLD));c.drawText(s,x,y,p);}
    private void box(Canvas c,float l,float t,float r,float b,float rad,int col){p.setStyle(Paint.Style.FILL);p.setShader(null);p.setColor(col);c.drawRoundRect(l,t,r,b,rad,rad,p);}
    private void outline(Canvas c,float l,float t,float r,float b,float rad,float sw,int col){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(sw);p.setShader(null);p.setColor(col);c.drawRoundRect(l,t,r,b,rad,rad,p);}
    private void background(Canvas c){p.setShader(new LinearGradient(0,0,0,H,Color.rgb(2,7,24),Color.rgb(15,2,31),Shader.TileMode.CLAMP));c.drawRect(0,0,W,H,p);p.setShader(null);for(O s:stars){float x=s.x/1000f*W,y=s.y/1800f*H;p.setStyle(Paint.Style.FILL);p.setColor(Color.argb(90+(int)(s.vy*45),100,205,255));c.drawCircle(x,y,s.r,p);}p.setStyle(Paint.Style.STROKE);p.setColor(Color.argb(22,80,190,255));for(int y=80;y<H;y+=110)c.drawLine(0,y,W,y,p);}
    @Override protected void onDraw(Canvas c){W=getWidth();H=getHeight();if(mode==PLAY)game(c);else if(mode==CLEAR)clear(c);else if(mode==DEAD)dead(c);else menu(c);}
    private void menu(Canvas c){background(c);txt(c,"SKY WINGS",W/2,62,40,Color.WHITE,Paint.Align.CENTER);txt(c,"1942 REBORN",W/2,92,17,Color.rgb(255,194,55),Paint.Align.CENTER);txt(c,"NEON SKY • ORIGINAL ARCADE",W/2,114,10,Color.rgb(90,215,255),Paint.Align.CENTER);drawShow(c,W/2,190,ship);box(c,10,270,W-10,455,22,Color.argb(225,5,13,34));outline(c,10,270,W-10,455,22,2,Color.rgb(25,125,185));txt(c,"CHOOSE YOUR FIGHTER",W/2,299,15,Color.WHITE,Paint.Align.CENTER);float gap=5,left=15,cw=(W-30-gap*4)/5f;for(int i=0;i<5;i++){float l=left+i*(cw+gap),r=l+cw;boolean sel=i==ship;box(c,l,315,r,412,12,sel?Color.argb(185,8,82,115):Color.argb(130,8,27,48));outline(c,l,315,r,412,12,sel?3:1,sel?Color.rgb(70,235,255):Color.rgb(30,80,115));drawShip(c,(l+r)/2,358,.42f,i,false);txt(c,ships[i],(l+r)/2,398,7.2f,Color.WHITE,Paint.Align.CENTER);}box(c,24,472,W-24,540,17,Color.rgb(7,110,150));outline(c,24,472,W-24,540,17,2,Color.rgb(90,240,255));txt(c,"START MISSION  •  STAGE "+stage,W/2,515,16,Color.WHITE,Paint.Align.CENTER);txt(c,"TOUCH TO SELECT  •  DRAG TO FLY  •  AUTO FIRE",W/2,570,9.5f,Color.LTGRAY,Paint.Align.CENTER);txt(c,"COINS "+coins,W/2-12,603,13,Color.YELLOW,Paint.Align.RIGHT);txt(c,"GEMS "+gems,W/2+12,603,13,Color.CYAN,Paint.Align.LEFT);txt(c,"Ads only after boss defeat",W/2,H-22,10,Color.rgb(100,170,205),Paint.Align.CENTER);}
    private void drawShow(Canvas c,float x,float y,int v){p.setShader(new RadialGradient(x,y,130,Color.argb(130,20,180,255),Color.TRANSPARENT,Shader.TileMode.CLAMP));p.setStyle(Paint.Style.FILL);c.drawCircle(x,y,130,p);p.setShader(null);drawShip(c,x,y,1.12f,v,true);txt(c,"SELECTED // "+ships[v],x,y+102,10,Color.rgb(120,230,255),Paint.Align.CENTER);}
    private void start(){mode=PLAY;kills=0;target=8+Math.min(14,stage/2);boss=false;enemies.clear();shots.clear();enemyShots.clear();drops.clear();particles.clear();hp=Math.max(70,hp);px=W/2f;py=H-150;spawnClock=shotClock=enemyClock=0;last=System.currentTimeMillis();invalidate();}
    private void game(Canvas c){background(c);long now=System.currentTimeMillis(),el=Math.min(50,now-last);last=now;float dt=el/1000f;for(O s:stars){s.y+=75*s.vy*dt;if(s.y>1800)s.y=0;}spawnClock+=el;shotClock+=el;enemyClock+=el;if(!boss&&kills<target&&spawnClock>450&&enemies.size()<7){spawnClock=0;spawnEnemy();}if(!boss&&kills>=target&&enemies.isEmpty())spawnBoss();if(shotClock>165){shotClock=0;fire();}if(enemyClock>850){enemyClock=0;enemyFire();}update(dt);for(P q:particles)drawParticle(c,q);for(O s:shots)drawShot(c,s);for(O s:enemyShots)drawEnemyShot(c,s);for(O e:enemies)drawEnemy(c,e);for(O d:drops)drawDrop(c,d);drawShip(c,px,py,.9f,ship,true);hud(c);if(bombFlash){float a=1-(System.currentTimeMillis()-bombClock)/350f;if(a>0){p.setStyle(Paint.Style.FILL);p.setColor(Color.argb((int)(80*a),80,225,255));c.drawRect(0,0,W,H,p);}else bombFlash=false;}postInvalidateDelayed(16);}
    private void spawnEnemy(){int t=rnd.nextInt(6);O e=new O(35+rnd.nextFloat()*(W-70),-60,20+rnd.nextFloat()*10,t);e.vy=70+rnd.nextFloat()*70;e.hp=1+stage/7;enemies.add(e);burst(e.x,e.y,8,enemyC[t]);}
    private void spawnBoss(){boss=true;O e=new O(W/2f,-105,70,10);e.hp=90+stage*16;e.vy=55;enemies.add(e);burst(e.x,e.y,35,Color.rgb(205,70,255));}
    private void update(float dt){for(O s:shots){s.y-=850*dt;if(s.y<-50)s.alive=false;}for(O s:enemyShots){s.x+=s.vx*dt;s.y+=s.vy*dt;if(s.y>H+40||s.x<-40||s.x>W+40)s.alive=false;}for(O e:enemies){e.y+=e.vy*dt;if(e.type==10){e.x=W/2f+(float)Math.sin(System.currentTimeMillis()*.0014)*W*.30f;e.vy=e.y<155?55:4;}else{e.x+=Math.sin(e.y*.018+e.type)*45*dt;if(e.y>H+80)e.alive=false;}}for(O d:drops){d.y+=130*dt;if(Math.hypot(d.x-px,d.y-py)<55){d.alive=false;collect(d.type);burst(d.x,d.y,12,Color.CYAN);}if(d.y>H+40)d.alive=false;}for(O s:shots)if(s.alive)for(O e:enemies)if(e.alive&&Math.hypot(s.x-e.x,s.y-e.y)<e.r+14){s.alive=false;e.hp--;burst(e.x,e.y,4,e.type==10?Color.MAGENTA:enemyC[e.type%6]);if(e.hp<=0){e.alive=false;kill(e);}}for(O s:enemyShots)if(s.alive&&Math.hypot(s.x-px,s.y-py)<24){s.alive=false;if(shield>0)shield--;else hp-=8;burst(px,py,12,Color.CYAN);}for(O e:enemies)if(e.alive&&Math.hypot(e.x-px,e.y-py)<e.r+26){e.alive=false;if(shield>0)shield--;else hp-=18;burst(px,py,18,Color.RED);}particlesUpdate(dt);clean(shots);clean(enemyShots);clean(enemies);clean(drops);if(boss&&enemies.isEmpty()){score+=stage*10000;coins+=stage*250;gems+=Math.max(1,stage/2);for(int i=0;i<8;i++)drops.add(new O(W/2f+(rnd.nextFloat()-.5f)*220,H*.40f+(rnd.nextFloat()-.5f)*120,18,i%12));mode=CLEAR;invalidate();}if(hp<=0&&mode==PLAY){mode=DEAD;invalidate();}}
    private void kill(O e){if(e.type==10){burst(e.x,e.y,70,Color.MAGENTA);return;}kills++;score+=100+stage*20;coins+=5+stage;burst(e.x,e.y,24,enemyC[e.type%6]);if(rnd.nextFloat()<.98)drops.add(new O(e.x,e.y,17,rnd.nextInt(12)));}
    private void collect(int t){if(t==0||t==2)power=Math.min(5,power+1);else if(t==1)power=Math.min(5,power+2);else if(t==3)shield=Math.min(3,shield+1);else if(t==5)hp=Math.min(100,hp+30);else if(t==6)coins+=100;else if(t==7)gems+=5;else if(t==8)score+=500;else if(t==9)bomb=Math.min(4,bomb+1);else if(t==10){for(O e:enemies)if(e.type!=10)e.hp-=5;}else power=5;}
    private void fire(){int n=power>=4?3:power>=2?2:1;for(int i=0;i<n;i++)shots.add(new O(px+(i-(n-1)/2f)*17,py-42,6,0));burst(px,py-42,3,shipC[ship]);}
    private void enemyFire(){if(enemies.isEmpty())return;O t=enemies.get(rnd.nextInt(enemies.size()));float dx=px-t.x,dy=py-t.y,len=(float)Math.max(1,Math.hypot(dx,dy));O s=new O(t.x,t.y+20,8,0);s.vx=dx/len*155;s.vy=dy/len*155;enemyShots.add(s);}
    private void clean(ArrayList<O>a){for(int i=a.size()-1;i>=0;i--)if(!a.get(i).alive)a.remove(i);}
    private void burst(float x,float y,int n,int c){for(int i=0;i<n&&particles.size()<260;i++){double a=rnd.nextDouble()*Math.PI*2;float sp=35+rnd.nextFloat()*180;particles.add(new P(x,y,(float)Math.cos(a)*sp,(float)Math.sin(a)*sp,.25f+rnd.nextFloat()*.55f,2+rnd.nextFloat()*6,c));}}
    private void particlesUpdate(float dt){for(P q:particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=.97f;q.vy*=.97f;q.life-=dt;}for(int i=particles.size()-1;i>=0;i--)if(particles.get(i).life<=0)particles.remove(i);}
    private void drawParticle(Canvas c,P q){p.setStyle(Paint.Style.FILL);float a=Math.max(0,q.life/.8f);p.setColor(Color.argb((int)(220*a),Color.red(q.c),Color.green(q.c),Color.blue(q.c)));c.drawCircle(q.x,q.y,q.size*a,p);}
    private void drawShot(Canvas c,O s){p.setStyle(Paint.Style.FILL);p.setColor(Color.argb(70,40,220,255));c.drawOval(s.x-9,s.y-25,s.x+9,s.y+25,p);p.setColor(Color.WHITE);c.drawRoundRect(s.x-3,s.y-17,s.x+3,s.y+17,3,3,p);}
    private void drawEnemyShot(Canvas c,O s){p.setStyle(Paint.Style.FILL);p.setColor(Color.argb(80,255,30,130));c.drawCircle(s.x,s.y,12,p);p.setColor(Color.rgb(255,80,155));c.drawCircle(s.x,s.y,5,p);}
    private void drawShip(Canvas c,float x,float y,float sc,int v,boolean glow){int col=shipC[Math.floorMod(v,5)];if(glow){p.setShader(new RadialGradient(x,y,70*sc,Color.argb(130,Color.red(col),Color.green(col),Color.blue(col)),Color.TRANSPARENT,Shader.TileMode.CLAMP));p.setStyle(Paint.Style.FILL);c.drawCircle(x,y,70*sc,p);p.setShader(null);}Path a=new Path();a.moveTo(x,y-48*sc);a.lineTo(x-15*sc,y-18*sc);a.lineTo(x-43*sc,y+16*sc);a.lineTo(x-19*sc,y+13*sc);a.lineTo(x-27*sc,y+38*sc);a.lineTo(x,y+25*sc);a.lineTo(x+27*sc,y+38*sc);a.lineTo(x+19*sc,y+13*sc);a.lineTo(x+43*sc,y+16*sc);a.lineTo(x+15*sc,y-18*sc);a.close();p.setStyle(Paint.Style.FILL);p.setShader(new LinearGradient(x,y-50*sc,x,y+40*sc,Color.WHITE,col,Shader.TileMode.CLAMP));c.drawPath(a,p);p.setShader(null);p.setColor(Color.rgb(20,35,55));Path w=new Path();w.moveTo(x,y-27*sc);w.lineTo(x-10*sc,y-4*sc);w.lineTo(x+10*sc,y-4*sc);w.close();c.drawPath(w,p);p.setColor(Color.WHITE);c.drawCircle(x,y-9*sc,3*sc,p);p.setColor(col);c.drawOval(x-6*sc,y+22*sc,x+6*sc,y+48*sc,p);}
    private void drawEnemy(Canvas c,O e){int col=e.type==10?Color.rgb(210,65,255):enemyC[e.type%6];if(e.type==10){p.setStyle(Paint.Style.FILL);p.setShader(new RadialGradient(e.x,e.y,105,Color.argb(150,210,50,255),Color.TRANSPARENT,Shader.TileMode.CLAMP));c.drawCircle(e.x,e.y,105,p);p.setShader(null);Path b=new Path();b.moveTo(e.x,e.y-65);b.lineTo(e.x-70,e.y-15);b.lineTo(e.x-48,e.y+45);b.lineTo(e.x,e.y+62);b.lineTo(e.x+48,e.y+45);b.lineTo(e.x+70,e.y-15);b.close();p.setColor(Color.rgb(50,22,75));c.drawPath(b,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(7);p.setColor(col);c.drawPath(b,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(255,70,190));c.drawCircle(e.x,e.y,25,p);p.setColor(Color.WHITE);c.drawCircle(e.x,e.y,9,p);p.setColor(Color.rgb(40,10,65));c.drawCircle(e.x,e.y,4,p);return;}p.setStyle(Paint.Style.FILL);p.setShader(new RadialGradient(e.x,e.y,35,Color.argb(170,Color.red(col),Color.green(col),Color.blue(col)),Color.TRANSPARENT,Shader.TileMode.CLAMP));c.drawCircle(e.x,e.y,35,p);p.setShader(null);Path q=new Path();q.moveTo(e.x,e.y-25);q.lineTo(e.x-26,e.y+10);q.lineTo(e.x-12,e.y+25);q.lineTo(e.x,e.y+15);q.lineTo(e.x+12,e.y+25);q.lineTo(e.x+26,e.y+10);q.close();p.setColor(col);c.drawPath(q,p);p.setColor(Color.rgb(20,25,45));c.drawCircle(e.x,e.y-2,8,p);p.setColor(Color.WHITE);c.drawCircle(e.x,e.y-4,3,p);}
    private void drawDrop(Canvas c,O d){int col= d.type==3?Color.CYAN:d.type==5?Color.GREEN:d.type==6?Color.YELLOW:d.type==7?Color.MAGENTA:Color.rgb(90,220,255);p.setStyle(Paint.Style.FILL);p.setShader(new RadialGradient(d.x,d.y,30,Color.argb(120,Color.red(col),Color.green(col),Color.blue(col)),Color.TRANSPARENT,Shader.TileMode.CLAMP));c.drawCircle(d.x,d.y,30,p);p.setShader(null);p.setColor(col);c.drawCircle(d.x,d.y,14,p);p.setColor(Color.WHITE);p.setTextSize(13);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);String s=d.type==3?"S":d.type==5?"+":d.type==6?"$":d.type==7?"♦":d.type==9?"B":"✦";c.drawText(s,d.x,d.y+5,p);}
    private void hud(Canvas c){box(c,8,8,W-8,58,16,Color.argb(185,4,12,30));txt(c,"STAGE "+stage,18,29,12,Color.WHITE,Paint.Align.LEFT);txt(c,"SCORE "+score,W/2,29,12,Color.WHITE,Paint.Align.CENTER);txt(c,"HP",18,49,9,Color.WHITE,Paint.Align.LEFT);box(c,42,40,145,51,5,Color.DKGRAY);box(c,42,40,42+103*hp/100f,51,5,Color.rgb(40,225,125));txt(c,"POWER "+power,158,49,9,Color.CYAN,Paint.Align.LEFT);txt(c,"BOMB "+bomb,W-18,29,11,Color.YELLOW,Paint.Align.RIGHT);if(boss){txt(c,"NEON WARDEN",W/2,80,11,Color.rgb(255,90,220),Paint.Align.CENTER);O b=enemies.isEmpty()?null:enemies.get(0);if(b!=null){box(c,35,88,W-35,98,5,Color.DKGRAY);box(c,35,88,(W-35)-(W-70)*(1-b.hp/(float)(90+stage*16)),98,5,Color.MAGENTA);}}box(c,16,H-82,112,H-20,20,Color.argb(175,5,20,42));outline(c,16,H-82,112,H-20,20,2,Color.rgb(40,145,190));txt(c,"BOMB",64,H-43,12,Color.YELLOW,Paint.Align.CENTER);txt(c,"TAP",64,H-26,8,Color.LTGRAY,Paint.Align.CENTER);}
    private void clear(Canvas c){background(c);txt(c,"STAGE CLEAR",W/2,180,34,Color.WHITE,Paint.Align.CENTER);txt(c,"NEON WARDEN DESTROYED",W/2,215,13,Color.rgb(255,100,220),Paint.Align.CENTER);txt(c,"SCORE  "+score,W/2,260,16,Color.YELLOW,Paint.Align.CENTER);box(c,25,320,W-25,390,18,Color.rgb(7,105,145));outline(c,25,320,W-25,390,18,2,Color.CYAN);txt(c,"WATCH AD • NEXT STAGE",W/2,363,16,Color.WHITE,Paint.Align.CENTER);box(c,55,420,W-55,480,16,Color.rgb(18,45,65));txt(c,"CONTINUE WITHOUT AD",W/2,458,12,Color.LTGRAY,Paint.Align.CENTER);txt(c,"Ad appears only after the boss.",W/2,530,10,Color.rgb(110,175,205),Paint.Align.CENTER);}
    private void dead(Canvas c){background(c);txt(c,"MISSION FAILED",W/2,230,32,Color.WHITE,Paint.Align.CENTER);txt(c,"SCORE "+score,W/2,270,15,Color.YELLOW,Paint.Align.CENTER);box(c,45,330,W-45,395,17,Color.rgb(115,35,65));txt(c,"RETRY STAGE",W/2,370,15,Color.WHITE,Paint.Align.CENTER);}
    @Override public boolean onTouchEvent(MotionEvent e){float x=e.getX(),y=e.getY();switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:performClick();if(mode==MENU){if(y>=310&&y<=425){float gap=5,left=15,cw=(W-30-gap*4)/5f;int pick=(int)((x-left)/(cw+gap));if(pick>=0&&pick<5){float l=left+pick*(cw+gap);if(x>=l&&x<=l+cw){ship=pick;invalidate();return true;}}}if(y>=455&&y<=560){start();return true;}}else if(mode==PLAY){if(y>H-115&&x<135){if(bomb>0){bomb--;bombFlash=true;bombClock=System.currentTimeMillis();for(O en:enemies)if(en.type!=10){en.hp-=5;if(en.hp<=0){en.alive=false;kill(en);}}burst(px,py,35,Color.CYAN);}return true;}px=Math.max(30,Math.min(W-30,x));py=Math.max(90,Math.min(H-90,y));return true;}else if(mode==DEAD){if(y>300&&y<430){hp=100;power=1;shield=1;start();return true;}}else if(mode==CLEAR){if(y>290&&y<410){try{Intent i=new Intent(Intent.ACTION_VIEW, Uri.parse(MONETAG_URL));i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);getContext().startActivity(i);}catch(Exception ignored){}stage++;mode=MENU;invalidate();return true;}if(y>410&&y<500){stage++;mode=MENU;invalidate();return true;}return true;case MotionEvent.ACTION_MOVE:if(mode==PLAY){px=Math.max(30,Math.min(W-30,x));py=Math.max(90,Math.min(H-90,y));return true;}return true;case MotionEvent.ACTION_UP:if(mode==PLAY){px=Math.max(30,Math.min(W-30,x));py=Math.max(90,Math.min(H-90,y));}return true;}return true;}
    @Override public boolean performClick(){super.performClick();return true;}
}